### ISSUE TITLE
House Preference

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#103]
I had a preference house when i was using android. When i logged in using iphone it did not go to the default house. Wait, checked it again, the preference is not working. Wait checked it again, its happening when you sign out and then sign in.

**Comment by abhishek-vikilabs** [comment]
Need to resolve a client side API call for edit preference. Currently getting a "User does not exist" error from the api.

**Comment by abhishek-vikilabs** [comment]
Added a dependency on Chinmay for API verification, as we are getting an error from the server. Added an issue with the issue number 255.

**Comment by e-ve** [comment]
@chinmaygit please review.
