### ISSUE TITLE
Keyboard pops up when entering DOB during sign up

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#104]

**Comment by twice-the-mantis** [comment]
Keyboard still popping up for about 1-2 seconds before disappearing

**Comment by twice-the-mantis** [comment]
Also clashing with numeric keyboard

**Comment by twice-the-mantis** [comment]
Keypad not showing up but DOB selector reads "Schedule Date"

**Comment by twice-the-mantis** [comment]
resolved
