### ISSUE TITLE
Check box missing in the signup

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#107]
The last page of the sign up should have a check box for us to inform that they have accepted the terms and condition. Please verify with the designs.

**Comment by abhishek-vikilabs** [comment]
Currently the user is shown a text saying that "by clicking proceed i agree to the terms and conditions". So this is not hindering with the requirements.

**Comment by twice-the-mantis** [comment]
Edit starting line to : "By pressing on Finish,
