### ISSUE TITLE
When selecting female gender during Signup

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#111]
When we select female gender during signup and not select a default pic. The Default pic should be a female pic.

**Comment by abhishek-vikilabs** [comment]
I think this issue should be assigned to Akshar first then should be respectively assigned to us.

**Comment by artakshar** [comment]
I have raised an issue for this illustration. You can refer to the new issue at #314. I will keep updating there and for the asset notification I'll have it posted it here.
