### ISSUE TITLE
In profile page, when clearing the gender and saving causes app to crash.

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#117]

**Comment by bansaldhruv1** [comment]
actually retested, it happening for all the editable fields.

**Comment by twice-the-mantis** [comment]
gender still acting like free text

**Comment by e-ve** [comment]
after deleting the Name on profile page, and keeping as empty, the pop-up is coming saying User name cant be Empty.
But the deleted name was not showing.It should undo the name automatically.
