### ISSUE TITLE
Need pop up for no homes in preferences.

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#125]
When I have no homes and i go to the preferences screen and click select default home, nothing happens. It should throw a pop up saying there is no home to select from.

**Comment by artakshar** [comment]
Designed the popup for that case. Have uploaded it on drive. @abhishek-vikilabs @bansaldhruv1

**Comment by artakshar** [comment]
Uploaded designs for Android as well. @chinmaygit @bansaldhruv1

**Comment by artakshar** [comment]
@bansaldhruv1 Please review and close this issue if issue is solved.

**Comment by bansaldhruv1** [comment]
just make the content changes as suggested by Akash

**Comment by bansaldhruv1** [comment]
need to remove retry now.

**Comment by artakshar** [comment]
Changes are made to content. Additionally, I've also removed retry button now. You can check the designs [here](https://drive.google.com/open?id=0B5U4feCYc_3tS05zcEFMbG1lVHc).
