### ISSUE TITLE
trying to change access for a user when i cant

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#135]
According to the hierarchy if I cant change room access for a user and when I try to it does nothing. It should show some up popup mentioning that you cant change access or something. While saving it gives some error, firstly content of the error should be changed and secondly it should popup the message even why i try to change and not only when i try to save it.

**Comment by e-ve** [comment]
an Admin can't make a normal user as Admin . But it happens here.
