### ISSUE TITLE
popup for trying to change access

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#136]
According to the hierarchy if I cant change room access for a user and when I try to it does nothing. It should show some up popup mentioning that you cant change access or something.

**Comment by artakshar** [comment]
Uploaded popup designs for iOS and Android on Google Drive. @abhishek-vikilabs @chinmaygit @bansaldhruv1

**Comment by artakshar** [comment]
@bansaldhruv1 Please review and close this issue if issue is solved.

**Comment by artakshar** [comment]
We will be showing room names but will be kept disabled for users who do not have rights to change it. For instance, if a normal user views another user's profile s/he would shown disabled room names but if an admin views a normal user's s/he would have enabled room names which means s/he'd be authorised to change room access. @abhishek-vikilabs @chinmaygit @bansaldhruv1
