### ISSUE TITLE
Create empty screens for

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#158]
-- Network Issue
-- No homes
-- No rooms
-- Master Offline
-- loading

**Comment by artakshar** [comment]
Added Android and iOS No Internet (Network issue) empty screen/popup and uploaded them to Google Drive. @bansaldhruv1 @chinmaygit @abhishek-vikilabs

**Comment by artakshar** [comment]
Added Android and iOS "No Homes" empty screen and uploaded them to Google Drive. @bansaldhruv1

**Comment by artakshar** [comment]
Added Android and iOS "No Rooms" empty/popup screen and uploaded them to Google Drive. @bansaldhruv1

**Comment by artakshar** [comment]
I have uploaded designs for "Master Offline" Android and iOS on Google Drive. @bansaldhruv1

**Comment by artakshar** [comment]
@bansaldhruv1 You can find all of these empty states here:

Android: https://drive.google.com/open?id=0B5U4feCYc_3tMlpsUXV5ZWFOM1k
iOS: https://drive.google.com/open?id=0B5U4feCYc_3tMXN0MFNxZE1tbkk

**Comment by artakshar** [comment]
@bansaldhruv1 we have created a separate issue for Loading animation, So I believe this issue can be placed in "In Review". Could you review and close if issues are resolved.

**Comment by artakshar** [comment]
@bansaldhruv1 I have updated for no homes empty screen. Check it out at the above links.

**Comment by artakshar** [comment]
@bansaldhruv1 Creating assets for the empty states for No Energy Data and No Homes.
