### ISSUE TITLE
empty state for One touch themes

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#159]
The designs need to be exactly how @artakshar designed it.

**Comment by e-ve** [comment]
If I create a Theme with out Name, it does not allow me to choose the appliances and theme not created.
Looks good.


@bansaldhruv1  please review from the designing  view.

**Comment by e-ve** [comment]
If i create a one touch theme with the same name, id doesn't showing any error.
It takes me to the Device list, and When I tried to click SAVE changes, nothing happened.
