### ISSUE TITLE
Deleting and Adding Devices through Config page not being updated on the cloud

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#16]
When you add or delete a module in your config page, the module list is not being updated on the cloud.

**Comment by rallicknom** [comment]
This happened once. Not easy to replicate as it was a random issue. Bug description: Energy meter module was installed and room was named as Energy-1. Energy data was not being displayed in the app. Energy meter module was resetted and added again as Energy-2. Everything went down as expected on config page but on app side, changes didn't take place. Energy-1 was still there in the app. Energy module was resetted again and added as E-3. This time app got updated but Energy-1 is still there. One energy data point synced to the cloud and remaining haven't.

**Comment by battuashwik** [comment]
Fixed
