### ISSUE TITLE
Need to change the design for one touch themes card for edit.

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#163]
after completing give it to @abhishek-vikilabs.

**Comment by artakshar** [comment]
I have uploaded new designs on Google Drive @abhishek-vikilabs. @bansaldhruv1 please review and close this issue, if this issue is solved.

**Comment by bansaldhruv1** [comment]
can you also make a change for the implementing of the theme that looks like a power button.

**Comment by artakshar** [comment]
As we discussed, I have made several changes to One Touch Theme design. You can see the live version for iOS [here](https://marvelapp.com/16a74j7#9949656).
