### ISSUE TITLE
Not able to delete a schedule that has been executed.

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#182]
When you create a schedule and it has already been executed the you cant delete it. It should not be visible at all.

**Comment by abhishek-vikilabs** [comment]
The SSE API currently does not provide an event for the Schedule Deletion or Schedule Completed State. Thus the app can not delete the schedule. Also we do not have an API for fetching the schedule for one specific switch, thus the schedules can not be reloaded, without refreshing the main activity for that home.

**Comment by e-ve** [comment]
done
