### ISSUE TITLE
There is a UI bug in creating one touch theme

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#187]
Initially it should say save changes when no appliance is selected.

The button needs to be improved.

Needs to be conveyed to both @abishek-vikilabs @chinmaygit.

**Comment by artakshar** [comment]
Changes are made and latest designs are uploaded to Drive. Here, only iOS design required changes. @abhishek-vikilabs @bansaldhruv1

**Comment by artakshar** [comment]
@bansaldhruv1 Please review and close this issue.

**Comment by bansaldhruv1** [comment]
When no appliance is selected then no save option should be available. As soon as you select one appliance then it should be visible and again should disappear if all the appliance have been de-selected.

**Comment by artakshar** [comment]
I have uploaded designs on Google Drive and uploaded them to Marvelapp. You can see it live [here](https://marvelapp.com/16a74j7#9949659).
