### ISSUE TITLE
It says first name in the sign up page but user name in profile page.

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#189]
Needs to fixed and implemented in both ios and android.

**Comment by artakshar** [comment]
I have verified in the designs and notified @abhishek-vikilabs and @chinmaygit. Changes were required only on iOS end since android has no placeholder saying "User Name" in Edit Profile screen.

**Comment by artakshar** [comment]
@bansaldhruv1 Please review and close this issue if issue is solved.

**Comment by bansaldhruv1** [comment]
reassigning it to @abhishek-vikilabs

**Comment by twice-the-mantis** [comment]
checked
