### ISSUE TITLE
Create UX for Preset delete

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#205]
Share it with @chinmaygit @abhishek-vikilabs and @vishnu888 once you have completed it.

**Comment by artakshar** [comment]
@bansaldhruv1 I have uploaded latest designs for delete existing preset. Additionally, I have updated Marvelapp flow for [iOS](https://marvelapp.com/16a74j7#12181836) and [Android](https://marvelapp.com/degj28#12181814).
