### ISSUE TITLE
Clash between Preset and Scheduling

### ISSUE THREAD

**Issue by twice-the-mantis** [vikilabs-code/hombot-issues#208]
When a schedule is set for an appliance followed by a preset timing where both timings clash with each other, user must be given a message saying that appiance is already running  on schedule OR preset...whatever was set first

**Comment by chinmaygit** [comment]
Sure, right now it is showing toast message 'Invalid time set'.  will set message 'Appliance is already running on schedule OR preset'.

**Comment by twice-the-mantis** [comment]
This will be solved by using schedule active and preset - active icons which you can implement once akshar design them
