### ISSUE TITLE
New icons for Schedule and Preset timer

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#213]
We need better icons for Schedule and Preset timer so that it conveys the right visual message.

**Comment by artakshar** [comment]
@bansaldhruv1 Updated the minor changes to "Main Activity" (Android and iOS) and uploaded it on Marvelapp & Google Drive. Assets are generated too. @abhishek-vikilabs @chinmaygit

**Comment by artakshar** [comment]
@bansaldhruv1 Please review this issue and close, if issue is solved.
