### ISSUE TITLE
Energy graph wrongly displaying gridlines

### ISSUE THREAD

**Issue by twice-the-mantis** [vikilabs-code/hombot-issues#216]
In the energy graphs, gridlines inside the graph area are visible. No lines except X and Y axes should be visible

**Comment by twice-the-mantis** [comment]
Extra gridline also present at '0'

**Comment by chinmaygit** [comment]
There is bit of research involved for it.

**Comment by chinmaygit** [comment]
Grid lines are fixed, but bar width is still thin.
