### ISSUE TITLE
Ui/Ux enhancement for editing and setting one touch themes

### ISSUE THREAD

**Issue by twice-the-mantis** [vikilabs-code/hombot-issues#221]
As a user, it is not clear that clicking on almost 80% of the card opens the edit option. And it is not intuitive that one must click on the power button set the theme. Maybe use a switch icon that toggles

**Comment by artakshar** [comment]
We have changed the designs. You can check the live designs [here](https://marvelapp.com/16a74j7#9949656). This solution is part of closed issue #163. So please review if this is the same solution to this issue.
