### ISSUE TITLE
Antenna test for slave module

### ISSUE THREAD

**Issue by Nikhil123456789** [vikilabs-code/hombot-issues#231]
Salve module which we connected through extender is working without extender by using Antenna but  the problem is it didn't worked when we closed with metal surrounding.
@rallicknom once check this .

**Comment by rallicknom** [comment]
Related issue #230

The addition of antenna helped. To understand the collective impact when antenna is attached to all modules in a house, much work needs to be done - especially RSSI strength logging with and without the antenna for a week or so and then analyzing those results. 

At a price of 0.3 USD per antenna, it appears as a worthwhile addition to the modules.

Need to decide whether antenna stays inside the casing or comes out and sticks on the switchboard. Definitely latter will have better reception but installation will take a little longer.
