### ISSUE TITLE
UI for device offline.

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#241]

**Comment by artakshar** [comment]
I have come up with initial designs for Device Offline. I have divided the experience into two steps, first being notifying the users and second is where we indicate users which device is offline. We have couple of design solutions for each step. I've uploaded these designs to [Google Drive](https://drive.google.com/open?id=0B5U4feCYc_3tTWFYd3hXMVBHU0U).
