### ISSUE TITLE
Implement Add Member designs

### ISSUE THREAD

**Issue by artakshar** [vikilabs-code/hombot-issues#266]
We have updated designs since we faced an issue in user experience. In this design, after selecting a home and desired rooms, we can see the following [output](https://marvelapp.com/degj28#12248859). You can see the live version [here.](https://marvelapp.com/degj28#9600308)

**Comment by chinmaygit** [comment]
links are not redirecting to claimed designs. please fix the links...

**Comment by artakshar** [comment]
This is the link to the updated UI for Add Member. There were several Ui changes and I believe we've discussed it too. You can see the live version [here.](https://marvelapp.com/2002hjh)

**Comment by twice-the-mantis** [comment]
When I'm adding exisiting member, error says "Email not registered with Hombot" instead of "Email already member of home"

**Comment by artakshar** [comment]
UI is implemented as per designs. Display picture is kept on hold because we need a new API.

**Comment by chinmaygit** [comment]
Response from server is Email not registered with Hombot OR Response code 704.  @vishnu888 can look into it, and do the necessary changes...
