### ISSUE TITLE
One touch theme new designs implementation

### ISSUE THREAD

**Issue by artakshar** [vikilabs-code/hombot-issues#268]
We have made few changes in design, particularly the list of theme screen. You can refer to this live designs [here.](https://marvelapp.com/16a74j7#9949656)

**Comment by bansaldhruv1** [comment]
off button needs to be removed.

**Comment by bansaldhruv1** [comment]
it should be 3 devices automated and not 3 No. of devices automated.

**Comment by bansaldhruv1** [comment]
the delete icon is very small.

**Comment by bansaldhruv1** [comment]
the image is blurred for edit.

**Comment by bansaldhruv1** [comment]
drop down make the existing card smaller.

**Comment by e-ve** [comment]
@bansaldhruv1  please review.
the dropdown menu Like Android looks good.
In Android If u click a device(the check box), the dropdown menu comes automatically.
But in IOS, user have to click on device manually to view the Drop Down menu.(the user might forget which device have the drop down menu.)
