### ISSUE TITLE
Need API to Get Themes list for a particular Home.

### ISSUE THREAD

**Issue by abhishek-vikilabs** [vikilabs-code/hombot-issues#29]
We need a new API to fetch the list of themes for a particular home. Right now all the themes related data is available in the Get Home List API. So we fetch the whole list of homes to get the themes info. This is particularly done to keep the state of the themes consistent after they have been deleted or updated.

**Comment by chinmaygit** [comment]
Multiple issue under API changes, this issue comes under API Changes refer issue #84, closing this issue.
