### ISSUE TITLE
Hombot 7 - Fan regulator not working 

### ISSUE THREAD

**Issue by rallicknom** [vikilabs-code/hombot-issues#3]
At lower speeds, fan turns OFF. On / Off control is working correctly.

**Comment by battuashwik** [comment]
@rallicknom Just check by connecting the regulator on the other slot and check if its working

**Comment by rallicknom** [comment]
@battuashwik Checked the GPIO states of all pins controlling the regulator. At any speed, no GPIO was getting a HIGH signal. In the meanwhile, four ON/OFF devices connected to 595 IC were working perfectly fine. Seems like an issue in fan regulator code.

**Comment by rallicknom** [comment]
Issue was on app side. Instead of 0-255, we were sending 0-4.
