### ISSUE TITLE
The Activity Log API currently misses out on the appliance name. Thus API for Devices need to be fetched reiteratively.

### ISSUE THREAD

**Issue by abhishek-vikilabs** [vikilabs-code/hombot-issues#30]
The API usage can be reduced if the Activity Log API get additional info with appliance name in order to show the icon for the image.

We currently have to fetch the get devices list for that particular home along with the events log API to display the cells appropriately.

**Comment by chinmaygit** [comment]
Multiple issue under API changes, this issue comes under API Changes refer issue #84, closing this issue.
