### ISSUE TITLE
UX Issue for Fan Regulator Slider

### ISSUE THREAD

**Issue by artakshar** [vikilabs-code/hombot-issues#304]
So we have 5 states for a fan regulator slider and these states are Off, Low, Mid, High and Overriding App Control (where physical regulator takes over App regulator control). Showing these states using a slider is not intuitive interaction.

**Comment by artakshar** [comment]
I have come up with design solutions for fan regulator. You can see the live designs for [Android](https://marvelapp.com/degj28#9600318) and [iOS](https://marvelapp.com/16a74j7#9572558).

**Comment by bansaldhruv1** [comment]
have two designs. The second design should be changed to numbers.

**Comment by bansaldhruv1** [comment]
check with Akash for Manual.
