### ISSUE TITLE
Design updates for Configuration page

### ISSUE THREAD

**Issue by artakshar** [vikilabs-code/hombot-issues#306]
Need to update configuration page for additional features.

**Comment by bansaldhruv1** [comment]
with additional features, there is some refactoring in the current design.

**Comment by artakshar** [comment]
I have prototyped couple of things today.

1. Drop-down for the room name.
2. Profile drop-down which contains Change Password and Logout.
3. Change Password modal view.
4. Register Master modal view.

Additionally, I have prototyped it on Marvelapp. You can check the live version [here.](https://marvelapp.com/2157d11)

**Comment by artakshar** [comment]
I have updated the designs and added couple of features.

1. Designed UI for Adjust System Time.
2. Software updates modal screen.

**Comment by bansaldhruv1** [comment]
Adjust system time needs to be modified as discussed.

**Comment by bansaldhruv1** [comment]
Design for when wrong events.
