### ISSUE TITLE
App crashing when going to add member screen.

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#308]

**Comment by chinmaygit** [comment]
I got crash report of your phone from Main Activity screen. can you please recreate the issue once again and confirm the crash is from Add Member screen?.

**Comment by chinmaygit** [comment]
App is crashing on Main Activity screen before going to Add User Screen, to refer app log https://fabric.io/vikilabs/android/apps/com.vikilabs.hombot_android/issues/5741522cffcdc0425034cbd0

**Comment by chinmaygit** [comment]
App is crashing only on dhruv's phone... depends on phones state.. need to know more about issue and monitor phones state. keeping issue in ready...
