### ISSUE TITLE
Edit logo for Splash screen

### ISSUE THREAD

**Issue by artakshar** [vikilabs-code/hombot-issues#313]
We have updated our logo recently therefore we need to update the same changes in the splash screen for consistent branding.

**Comment by artakshar** [comment]
@chinmaygit I have uploaded assets for Splash screen on [Drive.](https://drive.google.com/open?id=0B5U4feCYc_3taVhRbzFzSGNValE)

**Comment by chinmaygit** [comment]
Thank you, will change the splash screens with the new ones...
