### ISSUE TITLE
False switch sensing during power failure

### ISSUE THREAD

**Issue by rallicknom** [vikilabs-code/hombot-issues#4]
@battuashwik - we agreed that some sort of ping check to device will be performed after any packet is received to test whether hardware is alive or not. This will help us discard the packet which was sent while the device was shutting down during a power failure.

The code was to be implemented on raspberry side.

**Comment by bansaldhruv1** [comment]
Has been fixed by Ashwik on the software side. Tested also.

**Comment by rallicknom** [comment]
Initially a resistor replacement was implemented to increase the time delay between ac power cut and logic level switch for the switch sense but it was creating trouble with user experience. Finally the delay was implemented using code.
