### ISSUE TITLE
Android: Delete Theme Icon Change

### ISSUE THREAD

**Issue by rallicknom** [vikilabs-code/hombot-issues#45]
Toast appears saying 701 after confirming delete.
Delete icon is very inconvenient to use. it needs to be bigger. Sometimes I don't get the confirmation dialog box.

**Comment by chinmaygit** [comment]
Need to discuss with @artakshar about designing new delete function..

**Comment by chinmaygit** [comment]
refer Issue #83 to track changes from @artakshar about icon design.
