### ISSUE TITLE
Flickering on bulbs connected to SCK pin

### ISSUE THREAD

**Issue by battuashwik** [vikilabs-code/hombot-issues#49]
Whenever arduino resets the bulbs connected on arduino pins start to flicker.

**Comment by rallicknom** [comment]
It's a bootloader bug/feature. Boot loader makes the SCK pin go LOW HIGH a couple of times and hence the flicker. It can be avoided by modifying the bootloader.

**Comment by rallicknom** [comment]
Bootloader modification might not be necessary. Just re compiling the bootloader with LED flash count set to zero should do the job.

@battuashwik : You need to figure out how to recompile the bootloader. I can tell you everything else required to get the desired effects.

**Comment by rallicknom** [comment]
Alternatively, we can get rid of bootloader altogether and use SPI directly for burning the final code to the micro-controller. This will also reduce one step - bootloader burning step.

**Comment by rallicknom** [comment]
We changed the bootloader with setting number of blinks to Zero. The issue went away. Chandan confirmed it after testing the pin status during startup - both when powered using Serial and External power. There was no pulsing on SCK pin whatsoever.

Closing the issue.
