### ISSUE TITLE
Push Notifications Tech Doc IOS

### ISSUE THREAD

**Issue by battuashwik** [vikilabs-code/hombot-issues#55]

**Comment by abhishek-vikilabs** [comment]
Adding a link for the Amazon Push Notification for ios. It has a detailed explanation given.  I will create a push notification certificate from the apple developer portal for the process to be moved ahead.

http://docs.aws.amazon.com/sns/latest/dg/mobile-push-apns.html

**Comment by abhishek-vikilabs** [comment]
Completed the Tech doc and will get it reviewed on Monday from Ashwik.
