### ISSUE TITLE
User flow for Hombot App

### ISSUE THREAD

**Issue by artakshar** [vikilabs-code/hombot-issues#57]
Create a user flow for future reference of the Hombot App's flow with respect to type of users (Guest, Admin, Super Admin).

**Comment by artakshar** [comment]
Initial flow chart submitted to @bansaldhruv1 . Waiting for new inputs and feedbacks.

**Comment by artakshar** [comment]
@bansaldhruv1 Please review and close this issue if issue is solved.

**Comment by bansaldhruv1** [comment]
Need to add 'can add members' for super admin and admin.

**Comment by artakshar** [comment]
I have added "add a member" for super admin and admin. You can view it [here](https://drive.google.com/open?id=0B5U4feCYc_3tc2RvV1JKUlQ4SDQ).
