### ISSUE TITLE
Delete button is small in size.

### ISSUE THREAD

**Issue by chinmaygit** [vikilabs-code/hombot-issues#83]
Delete icon used in One touch theme and Schedules is small in size, need to increase its dimensions.

**Comment by artakshar** [comment]
New asset uploaded on Google Drive.

**Comment by chinmaygit** [comment]
got new assets for delete icon.  please refer #45 for implementation on android side...

**Comment by chinmaygit** [comment]
got new assets for delete icon. please refer #45 for android implementation.

**Comment by artakshar** [comment]
@chinmaygit Please review and close this issue, if issue is solved.
