### ISSUE TITLE
Name and Description Editing of Houses

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#96]
When I try to edit the name or description of the house, 
--- firstly the UI is crappy. 
---Secondly when I try to save only one of the fields it does not save.
---When i login for the first time or make any edits for one house then the name and description take sometime to fill.

**Comment by twice-the-mantis** [comment]
---Secondly when I try to save only one of the fields it does not save : Still Occurring 

Other 2 Points: @bansaldhruv1 , please verify
