### ISSUE TITLE
Improve the UI for editing name and description of a house.

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#98]

**Comment by artakshar** [comment]
Uploaded popup design on Google Drive, which will tackle this error with native UI Components. @abhishek-vikilabs @bansaldhruv1

**Comment by artakshar** [comment]
@bansaldhruv1 Please review and close this issue if issue is solved.

**Comment by bansaldhruv1** [comment]
complete for android as well

**Comment by artakshar** [comment]
Added popup design for Android as well. New designs are uploaded on Google Drive and on Marvelapp. You can view it live [here](https://marvelapp.com/degj28#12196653).
