### ISSUE TITLE
Edit Designs for Add member

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#99]
Manish has an idea regarding the same. May be you can have a look at what he is saying.

**Comment by artakshar** [comment]
@bansaldhruv1 I have designed something for solving the existing problem of Add Member home selection. I have uploaded it on Google Drive and live version on [Android](https://marvelapp.com/degj28#9600308) & [iOS](https://marvelapp.com/16a74j7#9602028).

**Comment by artakshar** [comment]
I will make a new issue for new design concept for Add Member based on Manish's idea. I'll post the issue id here soon after I create issue.
